/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */
repositories {
  jcenter()
}

plugins {
  id("eu.rigeldev.kuberig") version "0.0.39"
}

kuberig {
  kubernetes("v1.16.1")
}
